# Generated by Django 3.2 on 2021-05-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210501_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='moderated',
            field=models.BooleanField(null=True),
        ),
    ]
